//
//  AllQuestions.swift
//  Athletiq
//
//  Created by 64005540 on 4/16/26.
//

import Foundation

let allQuestions: [Question] = [

    Question(question: "Which MLB team has won the most World Series titles?", options: ["Dodgers","Red Sox","Yankees","Cardinals"], correctAnswer: 2, category: "MLB", difficulty: "Easy"),
    Question(question: "How many innings are in a standard MLB game?", options: ["7","9","8","10"], correctAnswer: 1, category: "MLB", difficulty: "Easy"),
    Question(question: "Which MLB team plays home games at Fenway Park?", options: ["Red Sox","Yankees","Blue Jays","Tigers"], correctAnswer: 0, category: "MLB", difficulty: "Easy"),
    Question(question: "Who is known as \"The Big Unit\" in MLB?", options: ["Randy Johnson","Babe Ruth","Nolan Ryan","Cy Young"], correctAnswer: 0, category: "MLB", difficulty: "Easy"),
    Question(question: "Which MLB team is nicknamed the \"Cubbies\"?", options: ["Pirates","Cardinals","Giants","Cubs"], correctAnswer: 3, category: "MLB", difficulty: "Easy"),
    Question(question: "Which NFL team plays home games at Lambeau Field?", options: ["Bears","Rams","Vikings","Packers"], correctAnswer: 3, category: "NFL", difficulty: "Easy"),
    Question(question: "How many points is a touchdown worth?", options: ["6","7","3","1"], correctAnswer: 0, category: "NFL", difficulty: "Easy"),
    Question(question: "What is the length of an NFL field in yards?", options: ["100","110","120","130"], correctAnswer: 2, category: "NFL", difficulty: "Easy"),
    Question(question: "Which team drafted Aaron Rodgers?", options: ["Vikings","Packers","Jets","Patriots"], correctAnswer: 1, category: "NFL", difficulty: "Easy"),
    Question(question: "Who is nicknamed \"The King\" in the NBA?", options: ["Steph curry","Michael Jordan","LeBron James","Kevin Durant"], correctAnswer: 2, category: "NBA", difficulty: "Easy"),
    Question(question: "How many players are on an NBA team on the court?", options: ["5","6","7","4"], correctAnswer: 0, category: "NBA", difficulty: "Easy"),
    Question(question: "Which NBA team is based in Toronto?", options: ["Cavs","Celtics","Knicks","Raptors"], correctAnswer: 3, category: "NBA", difficulty: "Easy"),
    Question(question: "Which NBA team wears green uniforms?", options: ["Celtics","Lakers","Bulls","Warriors"], correctAnswer: 0, category: "NBA", difficulty: "Easy"),
    Question(question: "Which soccer player is known as \"CR7\"?", options: ["Cristiano Ronaldo","Lionel Messi","Neymar","Kylian Mbappe"], correctAnswer: 0, category: "Soccer", difficulty: "Easy"),
    Question(question: "How many players are on a soccer team on the field?", options: ["10","11","12","9"], correctAnswer: 1, category: "Soccer", difficulty: "Easy"),
    Question(question: "Which country hosted the 2018 FIFA World Cup?", options: ["France","Brazil","Russia","Qatar"], correctAnswer: 2, category: "Soccer", difficulty: "Easy"),
    Question(question: "Which soccer team is nicknamed \"The Red Devils\"?", options: ["Chelsea","Liverpool","Manchester United","Arsenal"], correctAnswer: 2, category: "Soccer", difficulty: "Easy"),
    Question(question: "How long is a standard soccer match?", options: ["120 min","80 min","100 min","90 min"], correctAnswer: 3, category: "Soccer", difficulty: "Easy"),
    Question(question: "How many players are on the ice per team in a standard NHL game?", options: ["5","6","7","11"], correctAnswer: 2, category: "NHL", difficulty: "Easy"),
    Question(question: "Who is nicknamed \"The Great One\"?", options: ["Wayne Gretzky","Sidney Crosby","Alex Ovechkin","Bobby Orr"], correctAnswer: 0, category: "NHL", difficulty: "Easy"),
    Question(question: "How long is a standard NHL period?", options: ["15 min","20 min","25 min","30 min"], correctAnswer: 1, category: "NHL", difficulty: "Easy"),
    Question(question: "Which NHL team drafted Sidney Crosby?", options: ["Penguins","Flyers","Bruins","Capitals"], correctAnswer: 0, category: "NHL", difficulty: "Easy"),
    Question(question: "Which MLB team did Jackie Robinson break the color barrier with?", options: ["Dodgers","Giants","Yankees","Red Sox"], correctAnswer: 0, category: "MLB", difficulty: "Easy"),
    Question(question: "Which NBA player is nicknamed \"Black Mamba\"?", options: ["Steph curry","LeBron James","Kevin Durant","Kobe Bryant"], correctAnswer: 3, category: "NBA", difficulty: "Easy"),
    Question(question: "Which NFL team won Super Bowl I?", options: ["Cowboys","Chiefs","Packers","Steelers"], correctAnswer: 2, category: "NFL", difficulty: "Easy"),
    Question(question: "Which NBA team drafted Dirk Nowitzki?", options: ["Suns","Mavericks","Celtics","Spurs"], correctAnswer: 1, category: "NBA", difficulty: "Easy"),
    Question(question: "Which MLB player hit 73 home runs in a single season?", options: ["Babe Ruth","Barry Bonds","Mark McGwire","Sammy Sosa"], correctAnswer: 1, category: "MLB", difficulty: "Easy"),
    Question(question: "Which soccer country won UEFA Euro 2016?", options: ["Spain","France","Portugal","Germany"], correctAnswer: 2, category: "Soccer", difficulty: "Easy"),
    Question(question: "Which NHL team has the most Stanley Cup wins?", options: ["Canadiens","Maple Leafs","Red Wings","Bruins"], correctAnswer: 0, category: "NHL", difficulty: "Easy"),
    Question(question: "Which NFL team has the most Super Bowl wins of theese teams?", options: ["Patriots","Chiefs","Cowboys","49ers"], correctAnswer: 0, category: "NFL", difficulty: "Easy"),
    Question(question: "Who won the FIFA World Cup in 2018?", options: ["Germany","France","Brazil","Argentina"], correctAnswer: 1, category: "Soccer", difficulty: "Easy"),
    Question(question: "Which NBA team won the 2020 Finals?", options: ["Clippers","Heat","Celtics","Lakers"], correctAnswer: 3, category: "NBA", difficulty: "Easy"),
    Question(question: "Who is the all-time top scorer in international soccer?", options: ["Cristiano Ronaldo","Lionel Messi","Pele","Neymar"], correctAnswer: 0, category: "Soccer", difficulty: "Easy"),
    Question(question: "Which MLB pitcher threw a perfect game in 2012?", options: ["Justin Verlander","Felix Hernandez","Philip Humber","Roy Halladay"], correctAnswer: 2, category: "MLB", difficulty: "Easy"),
    Question(question: "Who holds the record for most strikeouts in MLB history?", options: ["Nolan Ryan","Randy Johnson","Pedro Martinez","Roger Clemens"], correctAnswer: 0, category: "MLB", difficulty: "Easy"),
    Question(question: "Who won the NFL MVP award in 2019?", options: ["Patrick Mahomes","Lamar Jackson","Russell Wilson","Aaron Rodgers"], correctAnswer: 0, category: "NFL", difficulty: "Easy"),
    Question(question: "Who won the NBA MVP in 2019?", options: ["Giannis Antetokounmpo","James Harden","Paul George","Kawhi Leonard"], correctAnswer: 0, category: "NBA", difficulty: "Easy"),
    Question(question: "Which country won the 2022 World Cup?", options: ["France","Argentina","Brazil","Germany"], correctAnswer: 1, category: "Soccer", difficulty: "Easy"),
    Question(question: "Which NBA player scored 100 points in a single game?", options: ["LeBron James","Michael Jordan","Kobe Bryant","Wilt Chamberlain"], correctAnswer: 3, category: "NBA", difficulty: "Easy"),
    Question(question: "Which NHL team won the Stanley Cup in 2025?", options: ["Tampa Bay Lightning","Dallas Stars","Florida Panthers","Vegas Golden Knights"], correctAnswer: 2, category: "NHL", difficulty: "Easy"),
    Question(question: "Who is known as \"The Refrigerator\" in NFL history?", options: ["Jerry Rice","William Perry","Emmitt Smith","Lawrence Taylor"], correctAnswer: 1, category: "NFL", difficulty: "Easy"),
    Question(question: "Which MLB team plays home games at Yankee Stadium?", options: ["Mets","Yankees","Tigers","Red Sox"], correctAnswer: 1, category: "MLB", difficulty: "Easy"),
    Question(question: "Which soccer club has won the most UEFA Champions League titles?", options: ["AC Milan","Barcelona","Real Madrid","Bayern Munich"], correctAnswer: 2, category: "Soccer", difficulty: "Easy"),
    Question(question: "How many points is a field goal in NFL?", options: ["6","3","1","2"], correctAnswer: 1, category: "NFL", difficulty: "Easy"),
    Question(question: "Which NBA team has never won a championship?", options: ["Spurs","Lakers","Wolves","Bulls"], correctAnswer: 2, category: "NBA", difficulty: "Easy"),
    Question(question: "Who is known as the slim reaper in the NBA?", options: ["Steph Curry","Michael Jordan","Anthony Edwards","Kevin Durant"], correctAnswer: 3, category: "NBA", difficulty: "Easy"),
    Question(question: "How many periods are in an NHL game?", options: ["2","3","4","5"], correctAnswer: 1, category: "NHL", difficulty: "Easy"),
    Question(question: "Who won the FIFA Ballon d’Or in 2021?", options: ["Robert Lewandowski","Cristiano Ronaldo","Neymar","Lionel Messi"], correctAnswer: 3, category: "Soccer", difficulty: "Easy"),
    Question(question: "How many players are on a soccer field per team?", options: ["12","10","11","9"], correctAnswer: 2, category: "Soccer", difficulty: "Easy"),
    Question(question: "Which MLB team is known as the \"Red Sox\"?", options: ["Boston","New York","Chicago","Los Angeles"], correctAnswer: 0, category: "MLB", difficulty: "Easy"),
    Question(question: "Which NBA team is based in Los Angeles?", options: ["Bulls","Lakers","Heat","Celtics"], correctAnswer: 1, category: "NBA", difficulty: "Easy"),
    Question(question: "Which NFL team’s colors are purple and gold?", options: ["Ravens","Packers","Saints","Vikings"], correctAnswer: 3, category: "NFL", difficulty: "Easy"),
    Question(question: "Which NHL team is based in Toronto?", options: ["Canadiens","Bruins","Maple Leafs","Rangers"], correctAnswer: 2, category: "NHL", difficulty: "Easy"),
    Question(question: "Which MLB team plays home games at Wrigley Field?", options: ["Giants","Cubs","Pirates","Cardinals"], correctAnswer: 1, category: "MLB", difficulty: "Easy"),
    Question(question: "Who is known as \"The Sultan of Swat\"?", options: ["Babe Ruth","Hank Aaron","Mickey Mantle","Lou Gehrig"], correctAnswer: 0, category: "MLB", difficulty: "Easy"),
    Question(question: "Which MLB team has a mascot named Mr. Met?", options: ["Dodgers","Yankees","Red Sox","Mets"], correctAnswer: 3, category: "MLB", difficulty: "Easy"),
    Question(question: "How many outs are in an inning per team?", options: ["4","2","5","3"], correctAnswer: 3, category: "MLB", difficulty: "Easy"),
    Question(question: "Which MLB player was nicknamed \"The Rocket\"?", options: ["Nolan Ryan","Pedro Martinez","Roger Clemens","Randy Johnson"], correctAnswer: 2, category: "MLB", difficulty: "Easy"),
    Question(question: "Who won the Super Bowl in 2021?", options: ["Buccaneers","Chiefs","Packers","Rams"], correctAnswer: 0, category: "NFL", difficulty: "Easy"),
    Question(question: "How many yards is a standard NFL field goal?", options: ["50","10","It Varies","3"], correctAnswer: 2, category: "NFL", difficulty: "Easy"),
    Question(question: "Which NFL team’s mascot is a horse named \"Blue\"?", options: ["Broncos","Dolphins","Seahawks","Colts"], correctAnswer: 3, category: "NFL", difficulty: "Easy"),
    Question(question: "Which NFL team’s colors are black and gold?", options: ["Saints","Ravens","Raiders","Steelers"], correctAnswer: 3, category: "NFL", difficulty: "Easy"),
    Question(question: "Which NFL quarterback is nicknamed \"TB12\"?", options: ["Patrick Mahomes","Drew Brees","Aaron Rodgers","Tom Brady"], correctAnswer: 3, category: "NFL", difficulty: "Easy"),
    Question(question: "Which NBA team has the nickname \"The Lakers\"?", options: ["Los Angeles","Miami","Chicago","Boston"], correctAnswer: 0, category: "NBA", difficulty: "Easy"),
    Question(question: "Which NBA Player has the most final assists?", options: ["Kobe Bryant","Magic Johnson","Michael Jordan","John Stockton"], correctAnswer: 1, category: "NBA", difficulty: "Easy"),
    Question(question: "Who won the NBA Finals MVP in 2020?", options: ["Kawhi Leonard","Jimmy Butler","LeBron James","Anthony Davis"], correctAnswer: 2, category: "NBA", difficulty: "Easy"),
    Question(question: "How many points is a free throw worth in NBA?", options: ["2","3","1","0"], correctAnswer: 2, category: "NBA", difficulty: "Easy"),
    Question(question: "Which NBA team plays at Madison Square Garden?", options: ["Bulls","Knicks","Nets","Celtics"], correctAnswer: 1, category: "NBA", difficulty: "Easy"),
    Question(question: "Which soccer team has Lionel Messi played for most recently?", options: ["Inter Miami","Barcelona","Manchester City","PSG"], correctAnswer: 0, category: "Soccer", difficulty: "Easy"),
    Question(question: "Which country won the FIFA World Cup in 2014?", options: ["Brazil","Germany","Argentina","Spain"], correctAnswer: 1, category: "Soccer", difficulty: "Easy"),
    Question(question: "Which soccer team’s colors are red and white, and they play at Old Trafford?", options: ["Liverpool","Arsenal","Chelsea","Manchester United"], correctAnswer: 3, category: "Soccer", difficulty: "Easy"),
    Question(question: "Who is the top scorer for the US men’s national soccer team?", options: ["Clint Dempsey","Christian Pulisic","Landon Donovan","Brian McBride"], correctAnswer: 2, category: "Soccer", difficulty: "Easy"),
    Question(question: "How many goals are in a hat-trick in soccer?", options: ["4","2","5","3"], correctAnswer: 3, category: "Soccer", difficulty: "Easy"),
    Question(question: "Which NHL team is nicknamed the \"Canadiens\"?", options: ["Toronto","Montreal","Chicago","Boston"], correctAnswer: 1, category: "NHL", difficulty: "Easy"),
    Question(question: "Which NHL player is known as \"Sid the Kid\"?", options: ["Wayne Gretzky","Connor McDavid","Alex Ovechkin","Sidney Crosby"], correctAnswer: 3, category: "NHL", difficulty: "Easy"),
    Question(question: "How many teams play in the NHL?", options: ["30","32","31","33"], correctAnswer: 1, category: "NHL", difficulty: "Easy"),
    Question(question: "Which NHL team plays at Madison Square Garden?", options: ["Devils","Flyers","Islanders","Rangers"], correctAnswer: 3, category: "NHL", difficulty: "Easy"),
    Question(question: "Which NHL goalie is nicknamed \"The Great One\"?", options: ["Martin Brodeur","Carey Price","Patrick Roy","Wayne Gretzky"], correctAnswer: 3, category: "NHL", difficulty: "Easy"),
    Question(question: "Who hit the \"Shot Heard 'Round the World\" in MLB?", options: ["Babe Ruth","Jackie Robinson","Hank Aaron","Bobby Thomson"], correctAnswer: 3, category: "MLB", difficulty: "Easy"),
    Question(question: "Which MLB team plays at Minute Maid Park?", options: ["Astros","Rangers","Yankees","Red Sox"], correctAnswer: 0, category: "MLB", difficulty: "Easy"),
    Question(question: "Which NFL team is based in Green Bay, Wisconsin?", options: ["Bears","Vikings","Packers","Lions"], correctAnswer: 2, category: "NFL", difficulty: "Easy"),
    Question(question: "Who won the first NBA championship?", options: ["Boston Celtics","Lakers","Philadelphia Warriors","Knicks"], correctAnswer: 2, category: "NBA", difficulty: "Easy"),
    Question(question: "Which NBA team is known for the \"Splash Brothers\"?", options: ["Lakers","Bulls","Warriors","Nets"], correctAnswer: 2, category: "NBA", difficulty: "Easy"),
    Question(question: "Which soccer player is from Argentina and won 6 Ballon d’Or awards?", options: ["Neymar","Lionel Messi","Cristiano Ronaldo","Kylian Mbappe"], correctAnswer: 1, category: "Soccer", difficulty: "Easy"),
    Question(question: "Which NHL team’s mascot is a dog named \"Bailey\"?", options: ["Canadiens","Maple Leafs","Rangers","Flyers"], correctAnswer: 1, category: "NHL", difficulty: "Easy"),
    Question(question: "How many bases are on a baseball field?", options: ["3","4","2","5"], correctAnswer: 1, category: "MLB", difficulty: "Easy"),
    Question(question: "Which NFL team won Super Bowl LIII?", options: ["Saints","Chiefs","Patriots","Rams"], correctAnswer: 2, category: "NFL", difficulty: "Easy"),
    Question(question: "Which NBA team’s colors are purple and gold?", options: ["Celtics","Lakers","Bulls","Spurs"], correctAnswer: 1, category: "NBA", difficulty: "Easy"),
    Question(question: "Who won the FIFA World Cup in 2010?", options: ["Netherlands","Germany","Spain","Brazil"], correctAnswer: 2, category: "Soccer", difficulty: "Easy"),
    Question(question: "Which NHL team plays at the United Center?", options: ["Red Wings","Canadiens","Rangers","Blackhawks"], correctAnswer: 3, category: "NHL", difficulty: "Easy"),
    Question(question: "Who was the first MLB player to hit 50 homers and steal 50 bases?", options: ["Satchel Paige","Jackie Robinson","Shohei Ohtani","Hank Aaron"], correctAnswer: 2, category: "MLB", difficulty: "Medium"),
    Question(question: "Which MLB team did Babe Ruth debut with?", options: ["Yankees","Dodgers","Giants","Red Sox"], correctAnswer: 3, category: "MLB", difficulty: "Medium"),
    Question(question: "Which MLB pitcher threw a perfect game in 2023?", options: ["Justin Verlander","Chris Sale","Domingo Germán","Roy Halladay"], correctAnswer: 2, category: "MLB", difficulty: "Medium"),
    Question(question: "Which MLB team plays at Petco Park?", options: ["Giants","Dodgers","Rockies","Padres"], correctAnswer: 3, category: "MLB", difficulty: "Medium"),
    Question(question: "Who won the 2004 AL MVP in MLB?", options: ["Alex Rodriguez","Manny Ramirez","Ichiro Suzuki","Vladimir Guerrero"], correctAnswer: 3, category: "MLB", difficulty: "Medium"),
    Question(question: "Who holds the record for most career interceptions in NFL history?", options: ["Deion Sanders","Charles Woodson","Ed Reed","Rod Woodson"], correctAnswer: 3, category: "NFL", difficulty: "Medium"),
    Question(question: "Which NFL team drafted Patrick Mahomes?", options: ["Titans","Ravens","Chiefs","Bills"], correctAnswer: 2, category: "NFL", difficulty: "Medium"),
    Question(question: "Who won the Super Bowl MVP in 2021?", options: ["Patrick Mahomes","Tom Brady","Aaron Rodgers","Josh Allen"], correctAnswer: 1, category: "NFL", difficulty: "Medium"),
    Question(question: "Which NFL quarterback has the most career passing yards?", options: ["Aaron Rodgers","Tom Brady","Drew Brees","Peyton Manning"], correctAnswer: 1, category: "NFL", difficulty: "Medium"),
    Question(question: "Which NFL team won the first Super Bowl in 1967?", options: ["Chiefs","Cowboys","Steelers","Packers"], correctAnswer: 3, category: "NFL", difficulty: "Medium"),
    Question(question: "Who won the NHL Hart Trophy (MVP) in 2019?", options: ["Connor McDavid","Alex Ovechkin","Nikita Kucherov","Patrick Kane"], correctAnswer: 2, category: "NHL", difficulty: "Medium"),
    Question(question: "Which NHL team is based in Las Vegas?", options: ["Sharks","Coyotes","Flames","Knights"], correctAnswer: 3, category: "NHL", difficulty: "Medium"),
    Question(question: "Which NHL team won the Stanley Cup in 2020?", options: ["Dallas Stars","Boston Bruins","Vegas Golden Knights","Tampa Bay Lightning"], correctAnswer: 3, category: "NHL", difficulty: "Medium"),
    Question(question: "Who is the all-time leading scorer for the NHL?", options: ["Mario Lemieux","Gordie Howe","Alexander Ovechkin","Wayne Gretzky"], correctAnswer: 3, category: "NHL", difficulty: "Medium"),
    Question(question: "Which NHL Player has the most blocks in NHL HIstory?", options: ["John Carlson","Alex Ovechkin","Ryan McDonagh","Alex Pietrangelo"], correctAnswer: 0, category: "NHL", difficulty: "Medium"),
    Question(question: "Who won the NBA Finals MVP in 2020?", options: ["Jimmy Butler","Kawhi Leonard","LeBron James","Anthony Davis"], correctAnswer: 2, category: "NBA", difficulty: "Medium"),
    Question(question: "Who won the NBA MVP in 2019?", options: ["James Harden","Paul George","Giannis Antetokounmpo","Kawhi Leonard"], correctAnswer: 2, category: "NBA", difficulty: "Medium"),
    Question(question: "Which NBA team drafted Dirk Nowitzki?", options: ["Suns","Celtics","Spurs","Mavericks"], correctAnswer: 3, category: "NBA", difficulty: "Medium"),
    Question(question: "Who holds the record for most NBA points in a career?", options: ["LeBron James","Michael Jordan","Kareem Abdul-Jabbar","Kobe Bryant"], correctAnswer: 2, category: "NBA", difficulty: "Medium"),
    Question(question: "Which NBA player is known as \"The Greek Freak\"?", options: ["Kristaps Porzingis","Anthony Davis","Giannis Antetokounmpo","Kevin Durant"], correctAnswer: 2, category: "NBA", difficulty: "Medium"),
    Question(question: "Which MLB player hit 73 home runs in a single season?", options: ["Mark McGwire","Sammy Sosa","Barry Bonds","Babe Ruth"], correctAnswer: 2, category: "MLB", difficulty: "Medium"),
    Question(question: "Which MLB team won the 2016 World Series?", options: ["Indians","Dodgers","Cubs","Red Sox"], correctAnswer: 2, category: "MLB", difficulty: "Medium"),
    Question(question: "Which MLB pitcher has the most career no-hitters?", options: ["Sandy Koufax","Cy Young","Randy Johnson","Nolan Ryan"], correctAnswer: 3, category: "MLB", difficulty: "Medium"),
    Question(question: "Which MLB team plays at Coors Field?", options: ["Giants","Dodgers","Padres","Rockies"], correctAnswer: 3, category: "MLB", difficulty: "Medium"),
    Question(question: "Who won AL MVP in 2016?", options: ["Jose Altuve","Mookie Betts","Mike Trout","David Ortiz"], correctAnswer: 2, category: "MLB", difficulty: "Medium"),
    Question(question: "Who holds the record for most career strikeouts in MLB?", options: ["Randy Johnson","Pedro Martinez","Nolan Ryan","Roger Clemens"], correctAnswer: 2, category: "MLB", difficulty: "Medium"),
    Question(question: "Which MLB team plays at PNC Park?", options: ["Cardinals","Cubs","Phillies","Pirates"], correctAnswer: 3, category: "MLB", difficulty: "Medium"),
    Question(question: "Who won the 2004 NL MVP in MLB?", options: ["Alex Rodriguez","Manny Ramirez","Barry Bonds","Ichiro Suzuki"], correctAnswer: 2, category: "MLB", difficulty: "Medium"),
    Question(question: "Who was the first African American to play in MLB’s modern era?", options: ["Satchel Paige","Jackie Robinson","Willie Mays","Hank Aaron"], correctAnswer: 1, category: "MLB", difficulty: "Medium"),
    Question(question: "Which MLB team did Aaron Judge debut with?", options: ["Yankees","Dodgers","Giants","Red Sox"], correctAnswer: 0, category: "MLB", difficulty: "Medium"),
    Question(question: "Who won the 2019 NFL MVP?", options: ["Lamar Jackson","Russell Wilson","Aaron Rodgers","Patrick Mahomes"], correctAnswer: 0, category: "NFL", difficulty: "Medium"),
    Question(question: "Which NFL team drafted Lamar Jackson?", options: ["Ravens","Titans","Bills","Chiefs"], correctAnswer: 0, category: "NFL", difficulty: "Medium"),
    Question(question: "Which NFL quarterback has the most career passing yards?", options: ["Drew Brees","Peyton Manning","Aaron Rodgers","Tom Brady"], correctAnswer: 3, category: "NFL", difficulty: "Medium"),
    Question(question: "Who holds the NFL record for rushing touchdowns?", options: ["Walter Payton","LaDainian Tomlinson","Marcus Allen","Emmitt Smith"], correctAnswer: 3, category: "NFL", difficulty: "Medium"),
    Question(question: "Which NFL team won the first Super Bowl in 1967?", options: ["Cowboys","Raiders","Chiefs","Packers"], correctAnswer: 3, category: "NFL", difficulty: "Medium"),
    Question(question: "Who won the 2020 Super Bowl MVP?", options: ["Tom Brady","Aaron Rodgers","Russell Wilson","Patrick Mahomes"], correctAnswer: 3, category: "NFL", difficulty: "Medium"),
    Question(question: "Which NFL team plays at Soldier Field?", options: ["Packers","Lions","Bears","Vikings"], correctAnswer: 2, category: "NFL", difficulty: "Medium"),
    Question(question: "Which NFL kicker scored the most points in a single season?", options: ["Adam Vinatieri","Matt Stover","Morten Andersen","Jason Myers"], correctAnswer: 3, category: "NFL", difficulty: "Medium"),
    Question(question: "Which NHL player has the most career goals?", options: ["Brett Hull","Mario Lemieux","Alexander Ovechkin","Wayne Gretzky"], correctAnswer: 3, category: "NHL", difficulty: "Medium"),
    Question(question: "Which NHL goalie has the most career wins?", options: ["Patrick Roy","Dominik Hasek","Henrik Lundqvist","Martin Brodeur"], correctAnswer: 3, category: "NHL", difficulty: "Medium"),
    Question(question: "Which NHL team won the Stanley Cup in 2015?", options: ["Dallas Stars","Chicago Blackhawks","Vegas Golden Knights","Tampa Bay Lightning"], correctAnswer: 1, category: "NHL", difficulty: "Medium"),
    Question(question: "Who won the Hart Trophy in 2020?", options: ["Connor McDavid","Alex Ovechkin","Leon Draisaitl","Nathan MacKinnon"], correctAnswer: 2, category: "NHL", difficulty: "Medium"),
    Question(question: "Which NHL team plays at Xfinity Mobile Arena?", options: ["Islanders","Devils","Rangers","Flyers"], correctAnswer: 3, category: "NHL", difficulty: "Medium"),
    Question(question: "Which NHL player is nicknamed \"Ovi\"?", options: ["Sidney Crosby","Connor McDavid","Alex Ovechkin","Wayne Gretzky"], correctAnswer: 2, category: "NHL", difficulty: "Medium"),
    Question(question: "Who is the all-time points leader in NHL history?", options: ["Jaromir Jagr","Gordie Howe","Mark Messier","Wayne Gretzky"], correctAnswer: 3, category: "NHL", difficulty: "Medium"),
    Question(question: "Who scored the Golden Goal in 2010 Winter Olympics hockey final?", options: ["Evgeni Malkin","Patrick Kane","Jonathan Toews","Sidney Crosby"], correctAnswer: 3, category: "NHL", difficulty: "Medium"),
    Question(question: "Who won the NBA Finals in 2019?", options: ["Warriors","Lakers","Raptors","Bucks"], correctAnswer: 2, category: "NBA", difficulty: "Medium"),
    Question(question: "Who won the NBA MVP in 2020?", options: ["LeBron James","Giannis Antetokounmpo","James Harden","Kawhi Leonard"], correctAnswer: 1, category: "NBA", difficulty: "Medium"),
    Question(question: "Which NBA team drafted Luka Dončić?", options: ["Hawks","Suns","Mavericks","Knicks"], correctAnswer: 0, category: "NBA", difficulty: "Medium"),
    Question(question: "Who holds the record for most points in a single NBA game?", options: ["Kobe Bryant","Michael Jordan","Wilt Chamberlain","Elgin Baylor"], correctAnswer: 2, category: "NBA", difficulty: "Medium"),
    Question(question: "Which NBA player is known as \"The Beard\"?", options: ["Stephen Curry","Kevin Durant","LeBron James","James Harden"], correctAnswer: 3, category: "NBA", difficulty: "Medium"),
    Question(question: "Who won the 2018 FIFA World Cup?", options: ["Croatia","Brazil","Germany","France"], correctAnswer: 3, category: "Soccer", difficulty: "Medium"),
    Question(question: "Who won the UEFA Euro 2016?", options: ["France","Germany","Portugal","Spain"], correctAnswer: 2, category: "Soccer", difficulty: "Medium"),
    Question(question: "Which soccer player is nicknamed \"La Pulga\"?", options: ["Cristiano Ronaldo","Neymar","Lionel Messi","Kylian Mbappe"], correctAnswer: 2, category: "Soccer", difficulty: "Medium"),
    Question(question: "Who is the all-time top scorer for Argentina?", options: ["Gabriel Batistuta","Diego Maradona","Lionel Messi","Sergio Agüero"], correctAnswer: 2, category: "Soccer", difficulty: "Medium"),
    Question(question: "Which soccer club has the most Champions League titles?", options: ["AC Milan","Barcelona","Liverpool","Real Madrid"], correctAnswer: 3, category: "Soccer", difficulty: "Medium"),
    Question(question: "Who won the 2010 FIFA World Cup?", options: ["Netherlands","Germany","Brazil","Spain"], correctAnswer: 3, category: "Soccer", difficulty: "Medium"),
    Question(question: "Who won the 2014 FIFA World Cup?", options: ["Argentina","Netherlands","Brazil","Germany"], correctAnswer: 3, category: "Soccer", difficulty: "Medium"),
    Question(question: "Which country hosted the 2002 FIFA World Cup?", options: ["Japan","Germany","South Korea","USA"], correctAnswer: 2, category: "Soccer", difficulty: "Medium"),
    Question(question: "Which soccer club plays at Camp Nou?", options: ["Real Madrid","PSG","Juventus","Barcelona"], correctAnswer: 3, category: "Soccer", difficulty: "Medium"),
    Question(question: "Who is the all-time top scorer for Portugal?", options: ["Eusebio","Nuno Gomes","Cristiano Ronaldo","Pauleta"], correctAnswer: 2, category: "Soccer", difficulty: "Medium"),
    Question(question: "Which MLB team has won the most consecutive World Series?", options: ["Red Sox","Dodgers","Giants","Yankees"], correctAnswer: 3, category: "MLB", difficulty: "Medium"),
    Question(question: "Which MLB team plays at Kauffman Stadium?", options: ["Cardinals","Cubs","Royals","Brewers"], correctAnswer: 2, category: "MLB", difficulty: "Medium"),
    Question(question: "Who holds the MLB record for stolen bases?", options: ["Lou Brock","Ty Cobb","Rickey Henderson","Tim Raines"], correctAnswer: 2, category: "MLB", difficulty: "Medium"),
    Question(question: "Who won Super Bowl XLIX?", options: ["Seahawks","Broncos","Patriots","Packers"], correctAnswer: 2, category: "NFL", difficulty: "Medium"),
    Question(question: "Which NFL team plays at Arrowhead Stadium?", options: ["Raiders","Colts","Titans","Chiefs"], correctAnswer: 3, category: "NFL", difficulty: "Medium"),
    Question(question: "Who won the 2017 NFL MVP?", options: ["Matt Ryan","Aaron Rodgers","Tom Brady","Drew Brees"], correctAnswer: 0, category: "NFL", difficulty: "Medium"),
    Question(question: "Which NHL team won the 2017 Stanley Cup?", options: ["Predators","Blues","Capitals","Penguins"], correctAnswer: 3, category: "NHL", difficulty: "Medium"),
    Question(question: "Which NHL player has the most career assists?", options: ["Mario Lemieux","Joe Sakic","Paul Coffey","Wayne Gretzky"], correctAnswer: 3, category: "NHL", difficulty: "Medium"),
    Question(question: "Who won the NBA MVP in 2018?", options: ["James Harden","LeBron James","Anthony Davis","Russell Westbrook"], correctAnswer: 0, category: "NBA", difficulty: "Medium"),
    Question(question: "Which NBA team plays at TD Garden?", options: ["Nets","Knicks","Celtics","Raptors"], correctAnswer: 2, category: "NBA", difficulty: "Medium"),
    Question(question: "Who is the all-time leading scorer in NBA playoffs?", options: ["Michael Jordan","Kareem Abdul-Jabbar","Kobe Bryant","LeBron James"], correctAnswer: 3, category: "NBA", difficulty: "Medium"),
    Question(question: "Who won the UEFA Euro 2012?", options: ["Germany","Italy","Portugal","Spain"], correctAnswer: 3, category: "Soccer", difficulty: "Medium"),
    Question(question: "Which soccer club plays at Allianz Arena?", options: ["Borussia Dortmund","PSG","Bayern Munich","Manchester City"], correctAnswer: 2, category: "Soccer", difficulty: "Medium"),
    Question(question: "Who won the FIFA Ballon d’Or in 2018?", options: ["Cristiano Ronaldo","Mohamed Salah","Lionel Messi","Luka Modrić"], correctAnswer: 3, category: "Soccer", difficulty: "Medium"),
    Question(question: "Who won the 1960 World Series?", options: ["Yankees","Dodgers","Pirates","Red Sox"], correctAnswer: 2, category: "MLB", difficulty: "Hard"),
    Question(question: "Which MLB player had a 56-game hitting streak?", options: ["Ty Cobb","Stan Musial","Lou Gehrig","Joe DiMaggio"], correctAnswer: 3, category: "MLB", difficulty: "Hard"),
    Question(question: "Who holds the MLB single-season home run record?", options: ["Babe Ruth","Mark McGwire","Sammy Sosa","Barry Bonds"], correctAnswer: 3, category: "MLB", difficulty: "Hard"),
    Question(question: "Which MLB pitcher threw a perfect game in 2010?", options: ["Felix Hernandez","Roy Halladay","Justin Verlander","Philip Humber"], correctAnswer: 1, category: "MLB", difficulty: "Hard"),
    Question(question: "Which MLB team has never won a World Series?", options: ["Rangers","Rockies","Marlins","Padres"], correctAnswer: 3, category: "MLB", difficulty: "Hard"),
    Question(question: "Who holds the NFL record for most career passing touchdowns?", options: ["Peyton Manning","Drew Brees","Brett Favre","Tom Brady"], correctAnswer: 3, category: "NFL", difficulty: "Hard"),
    Question(question: "Who was the youngest quarterback to start a Super Bowl?", options: ["Ben Roethlisberger","Dan Marino","Tom Brady","Patrick Mahomes"], correctAnswer: 3, category: "NFL", difficulty: "Hard"),
    Question(question: "Which NFL team won the 1966 Super Bowl?", options: ["Cowboys","Raiders","Chiefs","Packers"], correctAnswer: 3, category: "NFL", difficulty: "Hard"),
    Question(question: "Who has the most career rushing touchdowns in NFL history?", options: ["Walter Payton","LaDainian Tomlinson","Marcus Allen","Emmitt Smith"], correctAnswer: 3, category: "NFL", difficulty: "Hard"),
    Question(question: "Which NFL kicker scored the most points in a playoff history?", options: ["Adam Vinatieri","Matt Stover","Morten Andersen","David Akers"], correctAnswer: 0, category: "NFL", difficulty: "Hard"),
    Question(question: "Who holds the record for most goals in a single NHL season?", options: ["Brett Hull","Mario Lemieux","Alexander Ovechkin","Wayne Gretzky"], correctAnswer: 3, category: "NHL", difficulty: "Hard"),
    Question(question: "Which NHL goalie has the most playoff career wins?", options: ["Patrick Roy","Dominik Hasek","Henrik Lundqvist","Martin Brodeur"], correctAnswer: 0, category: "NHL", difficulty: "Hard"),
    Question(question: "Which NHL team has won the most Stanley Cups in a row?", options: ["Maple Leafs","Red Wings","Bruins","Canadiens"], correctAnswer: 3, category: "NHL", difficulty: "Hard"),
    Question(question: "Who was the USA goalie in the 2010 Olympics?", options: ["Evgeni Malkin","Ryan Miller","Jordan Binnington","Spencer Knight"], correctAnswer: 1, category: "NHL", difficulty: "Hard"),
    Question(question: "Who is the all-time points leader in the Stanley Cup for NHL?", options: ["Jean Béliveau","Gordie Howe","Mark Messier","Wayne Gretzky"], correctAnswer: 0, category: "NHL", difficulty: "Hard"),
    Question(question: "Who scored 83 points in a single NBA game?", options: ["Wilt Chamberlain","Michael Jordan","Bam Adebayo","Kobe Bryant"], correctAnswer: 2, category: "NBA", difficulty: "Hard"),
    Question(question: "Which NBA team won the 2004 Finals?", options: ["Lakers","Spurs","Celtics","Pistons"], correctAnswer: 3, category: "NBA", difficulty: "Hard"),
    Question(question: "Who holds the NBA record for most career assists?", options: ["Magic Johnson","Steve Nash","Jason Kidd","John Stockton"], correctAnswer: 3, category: "NBA", difficulty: "Hard"),
    Question(question: "Which NBA player scored 20 points in game 7 of the 2025 NBA Finals?", options: ["Pascal Siakam","Andrew Nembhard","Jalen Williams","Myles Turner"], correctAnswer: 2, category: "NBA", difficulty: "Hard"),
    Question(question: "Which soccer player won both Ballon d’Or and FIFA World Cup Golden Ball?", options: ["Luka Modrić","Kylian Mbappé","Cristiano Ronaldo","Lionel Messi"], correctAnswer: 3, category: "Soccer", difficulty: "Hard"),
    Question(question: "Who won the 2016 World Series MVP?", options: ["Anthony Rizzo","Javier Baez","Jon Lester","Ben Zobrist"], correctAnswer: 3, category: "MLB", difficulty: "Hard"),
    Question(question: "Who holds the MLB record for career triples?", options: ["Sam Crawford","Ty Cobb","Stan Musial","Willie Mays"], correctAnswer: 0, category: "MLB", difficulty: "Hard"),
    Question(question: "Which MLB player hit over 60 home runs in 1961?", options: ["Roger Maris","Mickey Mantle","Harmon Killebrew","Hank Aaron"], correctAnswer: 0, category: "MLB", difficulty: "Hard"),
    Question(question: "Which MLB team plays at Oriole Park at Camden Yards?", options: ["Orioles","Red Sox","Yankees","Rays"], correctAnswer: 0, category: "MLB", difficulty: "Hard"),
    Question(question: "Who was the first MLB player to reach 3,000 hits?", options: ["Cap Anson","Ty Cobb","Honus Wagner","Nap Lajoie"], correctAnswer: 0, category: "MLB", difficulty: "Hard"),
    Question(question: "Which NFL team has the least amount of Super Bowls?", options: ["Patriots","Steelers","Chiefs","Dolphins"], correctAnswer: 3, category: "NFL", difficulty: "Hard"),
    Question(question: "Who won the NFL MVP in 2018?", options: ["Patrick Mahomes","Drew Brees","Aaron Rodgers","Tom Brady"], correctAnswer: 3, category: "NFL", difficulty: "Hard"),
    Question(question: "Who has the most career interceptions in Playoff NFL history?", options: ["Ed Reed","Rod Woodson","Deion Sanders","Charles Woodson"], correctAnswer: 0, category: "NFL", difficulty: "Hard"),
    Question(question: "Which NFL team plays at U.S. Bank Stadium?", options: ["Vikings","Packers","Bears","Falcons"], correctAnswer: 0, category: "NFL", difficulty: "Hard"),
    Question(question: "Who won Super Bowl XLV?", options: ["Packers","Steelers","Patriots","Giants"], correctAnswer: 0, category: "NFL", difficulty: "Hard"),
    Question(question: "Which NHL Player has the most career hits?", options: ["Alexander Ovechkin","Cal Clutterbuck","Wayne Gretzky","Mario Lemieux"], correctAnswer: 1, category: "NHL", difficulty: "Hard"),
    Question(question: "Who won the Vezina Trophy in 2017?", options: ["Braden Holtby","Connor Hellebuyck","Sergei Bobrovsky","Henrik Lundqvist"], correctAnswer: 2, category: "NHL", difficulty: "Hard"),
    Question(question: "Which NHL team won the Stanley Cup in 2016?", options: ["Penguins","Sharks","Lightning","Blackhawks"], correctAnswer: 0, category: "NHL", difficulty: "Hard"),
    Question(question: "Who has the most career playoff points as a defensman in NHL history?", options: ["Paul Coffey","Mark Messier","Quin Hughes","Mario Lemieux"], correctAnswer: 0, category: "NHL", difficulty: "Hard"),
    Question(question: "Which NHL player is nicknamed \"The Russian Rocket\"?", options: ["Pavel Bure","Alexander Ovechkin","Sergei Fedorov","Ilya Kovalchuk"], correctAnswer: 0, category: "NHL", difficulty: "Hard"),
    Question(question: "Who holds the record for most points in a single NBA season as a bench player?", options: ["Ricky Pierce","Jordan Clarkson","Tre Mann","Moses Moody"], correctAnswer: 0, category: "NBA", difficulty: "Hard"),
    Question(question: "Which NBA team won the 1995 Finals?", options: ["Rockets","Magic","Bulls","Knicks"], correctAnswer: 0, category: "NBA", difficulty: "Hard"),
    Question(question: "Who won the NBA Finals MVP in 2017?", options: ["Kevin Durant","LeBron James","Kawhi Leonard","Stephen Curry"], correctAnswer: 0, category: "NBA", difficulty: "Hard"),
    Question(question: "Who holds the NBA record for most three-pointers made?", options: ["Stephen Curry","Ray Allen","Reggie Miller","James Harden"], correctAnswer: 0, category: "NBA", difficulty: "Hard"),
    Question(question: "Which NBA player is nicknamed \"The Logo\"?", options: ["Jerry West","Magic Johnson","Michael Jordan","Kobe Bryant"], correctAnswer: 0, category: "NBA", difficulty: "Hard"),
    Question(question: "Who scored the winning goal for France in the 2018 World Cup final?", options: ["Antoine Griezmann","Kylian Mbappé","Mario Mandzukic","Paul Pogba"], correctAnswer: 3, category: "Soccer", difficulty: "Hard"),
    Question(question: "Which country won the FIFA World Cup in 2006?", options: ["Italy","France","Germany","Brazil"], correctAnswer: 0, category: "Soccer", difficulty: "Hard"),
    Question(question: "Who won the 2014 FIFA World Cup Golden Ball?", options: ["Lionel Messi","Thomas Müller","Neymar","James Rodríguez"], correctAnswer: 0, category: "Soccer", difficulty: "Hard"),
    Question(question: "Which soccer player has the most international goals for Italy?", options: ["Cristiano Ronaldo","Gigi Riva","Pauleta","Luis Figo"], correctAnswer: 1, category: "Soccer", difficulty: "Hard"),
    Question(question: "Which soccer club won the 2014 Champions League?", options: ["Real Madrid","Liverpool","Bayern Munich","PSG"], correctAnswer: 0, category: "Soccer", difficulty: "Hard"),
    Question(question: "Who won the Copa America in 2019?", options: ["Brazil","Argentina","Chile","Uruguay"], correctAnswer: 0, category: "Soccer", difficulty: "Hard"),
    Question(question: "Who holds the MLB record for career RBIs?", options: ["Hank Aaron","Babe Ruth","Alex Rodriguez","Lou Gehrig"], correctAnswer: 0, category: "MLB", difficulty: "Hard"),
    Question(question: "Who has the farthest homerun in MLB history since 2010?", options: ["Aaron Judge","Bobby Witt","Mike Trout","Nomar Mazara"], correctAnswer: 3, category: "MLB", difficulty: "Hard"),
    Question(question: "Which MLB player hit over 60 home runs in 1998?", options: ["Mark McGwire","Sammy Sosa","Barry Bonds","Ken Griffey Jr."], correctAnswer: 0, category: "MLB", difficulty: "Hard"),
    Question(question: "Who won the 1996 NFL MVP?", options: ["Jerry Rice","Joe Montana","Brett Favre","Michael Irvin"], correctAnswer: 2, category: "NFL", difficulty: "Hard"),
    Question(question: "Which NFL Team came the closest to three peating?", options: ["Patriots","Seahawks","Chiefs","Panthers"], correctAnswer: 2, category: "NFL", difficulty: "Hard"),
    Question(question: "Who has the most career sacks in NFL history?", options: ["Bruce Smith","Reggie White","Kevin Greene","DeMarcus Ware"], correctAnswer: 0, category: "NFL", difficulty: "Hard"),
    Question(question: "Which NFL team plays at AT&T Stadium?", options: ["Cowboys","Giants","Eagles","Packers"], correctAnswer: 0, category: "NFL", difficulty: "Hard"),
    Question(question: "Who won the Stanley Cup in 2015?", options: ["Blackhawks","Rangers","Penguins","Kings"], correctAnswer: 0, category: "NHL", difficulty: "Hard"),
    Question(question: "Which NHL Player has the most played stanley cup games?", options: ["Wayne Gretzky","Henri Richard","Jaromir Jagr","Mark Messier"], correctAnswer: 1, category: "NHL", difficulty: "Hard"),
    Question(question: "Who won the 2019 Conn Smythe Trophy?", options: ["T.J. Oshie","Connor Mcdavid","Ryan O\'Reilly","Patrick Kane"], correctAnswer: 2, category: "NHL", difficulty: "Hard"),
    Question(question: "Who scored the most points in a single NHL game?", options: ["Darryl Sittler","Wayne Gretzky","Mario Lemieux","Phil Esposito"], correctAnswer: 0, category: "NHL", difficulty: "Hard"),
    Question(question: "Which NHL team plays in Winnipeg?", options: ["Jets","Oilers","Flames","Canucks"], correctAnswer: 0, category: "NHL", difficulty: "Hard"),
    Question(question: "Which NBA player has the most steals in NBA history?", options: ["Kobe Bryant","John Stockton","Michael Jordan","Elgin Baylor"], correctAnswer: 1, category: "NBA", difficulty: "Hard"),
    Question(question: "Which NBA team won the 2003 Finals?", options: ["Spurs","Lakers","Nets","Celtics"], correctAnswer: 0, category: "NBA", difficulty: "Hard"),
    Question(question: "Who has the NBA record for most tripple doubles?", options: ["Rusell Westbrook","Oscar Robertson","Nikola Jókic","LeBron James"], correctAnswer: 0, category: "NBA", difficulty: "Hard"),
    Question(question: "Which nba player had the highest 3pt % in 2014?", options: ["Steph Curry","Kobe Bryant","Tony Parker","Kyle Korver"], correctAnswer: 3, category: "NBA", difficulty: "Hard"),
    Question(question: "Which Soccer goalie has the most saves?", options: ["Lev Yashin","Manuel Neuer","Oliver Baumann","Gordon Banks"], correctAnswer: 2, category: "Soccer", difficulty: "Hard"),
    Question(question: "Which country hosted the 2010 FIFA World Cup?", options: ["South Africa","Brazil","Germany","Russia"], correctAnswer: 0, category: "Soccer", difficulty: "Hard"),
    Question(question: "Who won the 2018 FIFA World Cup Golden Boot?", options: ["Harry Kane","Antoine Griezmann","Kylian Mbappé","Romelu Lukaku"], correctAnswer: 0, category: "Soccer", difficulty: "Hard"),
    Question(question: "Which soccer club won the 2017 Champions League?", options: ["Real Madrid","Juventus","Barcelona","Bayern Munich"], correctAnswer: 0, category: "Soccer", difficulty: "Hard"),
    Question(question: "Who is the all-time leading scorer for France?", options: ["Oliver Giroud","Gabriel Batistuta","Diego Maradona","Sergio Agüero"], correctAnswer: 0, category: "Soccer", difficulty: "Hard"),
    Question(question: "Who won the Copa America in 2016?", options: ["Chile","Argentina","Brazil","Uruguay"], correctAnswer: 0, category: "Soccer", difficulty: "Hard"),
    Question(question: "Who holds the MLB record for career doubles?", options: ["Rickey Henderson","Tris Speaker","Ty Cobb","Tim Raines"], correctAnswer: 1, category: "MLB", difficulty: "Hard"),
    Question(question: "Which MLB team plays at Tropicana Field?", options: ["Royals","Cardinals","Rays","Brewers"], correctAnswer: 2, category: "MLB", difficulty: "Hard"),
    Question(question: "Who won Super Bowl XLL?", options: ["Patriots","Seahawks","Giants","Packers"], correctAnswer: 2, category: "NFL", difficulty: "Hard"),
    Question(question: "Which NFL team plays at Raymond James Stadium?", options: ["Chiefs","Raiders","Buccaneers","Titans"], correctAnswer: 2, category: "NFL", difficulty: "Hard"),
    Question(question: "Who won the 2012 NFL MVP?", options: ["Tom Brady","Matt Ryan","Aaron Rodgers","Drew Brees"], correctAnswer: 2, category: "NFL", difficulty: "Hard"),
    Question(question: "Which NHL team won the 2000 Stanley Cup?", options: ["Penguins","Predators","Devils","Capitals"], correctAnswer: 2, category: "NHL", difficulty: "Hard"),
    Question(question: "Which NHL player has the most career assists as a goalie?", options: ["Connor Ingram","Tristian Jarry","Tom Barrasso","Andrei Vasilevskiy"], correctAnswer: 2, category: "NHL", difficulty: "Hard"),
    Question(question: "Who won the NBA MVP in 2011?", options: ["Kobe Bryant","LeBron James","Derrick Rose","Anthony Davis"], correctAnswer: 2, category: "NBA", difficulty: "Hard"),
    Question(question: "Which NBA team plays at Ball Arena?", options: ["Celtics","Nets","Knicks","Nuggets"], correctAnswer: 3, category: "NBA", difficulty: "Hard"),
    Question(question: "Who is the all-time leading rebounder in the NBA Finals?", options: ["LeBron James","Bill Russell","Kareem Abdul-Jabbar","Shaquille O\'Neal"], correctAnswer: 1, category: "NBA", difficulty: "Hard"),
    Question(question: "Who won the UEFA Euro 2000?", options: ["Spain","France","Italy","Portugal"], correctAnswer: 1, category: "Soccer", difficulty: "Hard"),
    Question(question: "Which soccer club plays at Parc des Princes?", options: ["Bayern Munich","Borussia Dortmund","PSG","Manchester City"], correctAnswer: 2, category: "Soccer", difficulty: "Hard"),
    Question(question: "Who won the FIFA Ballon d’Or in 1995?", options: ["Luka Modrić","Jürgen Klinsmann","Jari Litmanen","George Weah"], correctAnswer: 3, category: "Soccer", difficulty: "Hard")
    
    ]
             
                                                            
                                                            
                                                            
                                                            
                                                            
                                                
